# Generated by Django 5.1.1 on 2024-10-01 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menutoko_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutoko',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
